'use strict';

const COMPTIA_SEC = [
  // ═══════════════════════════════════════════════════════════════
  // Domain 1: General Security Concepts (12%)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'SEC-1.1',
    domain: 'comptia',
    title: 'Security Controls Categories',
    content: 'Security controls are safeguards to reduce risk. Categories by function: Preventive (block attacks before they occur — firewalls, encryption, access controls), Detective (identify attacks in progress — IDS, SIEM, audit logs), Corrective (fix after incident — patching, restore from backup), Deterrent (discourage attackers — warning banners, security cameras), Compensating (alternative when primary control isn\'t feasible — monitoring when can\'t encrypt), Directive (dictate behavior — policies, procedures, training). Categories by implementation: Technical/Logical (software/hardware — firewalls, encryption, ACLs), Managerial/Administrative (policies, training, risk assessments), Operational (day-to-day procedures — guard patrols, change management), Physical (locks, fences, biometrics, mantrap/vestibule).',
    tags: ['controls', 'fundamentals', 'governance'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-1.2', 'SEC-5.1'],
    detection: 'Control assessment, security audit, gap analysis',
    mitigation: 'Implement defense-in-depth with controls from multiple categories and implementation types'
  },
  {
    id: 'SEC-1.2',
    domain: 'comptia',
    title: 'CIA Triad and Security Fundamentals',
    content: 'Confidentiality: prevent unauthorized disclosure (encryption, access controls, data masking). Integrity: prevent unauthorized modification (hashing, digital signatures, checksums, version control). Availability: ensure authorized access when needed (redundancy, load balancing, backups, DDoS protection). Additional concepts: Non-repudiation (proof of origin/delivery — digital signatures, audit logs), Authentication (verify identity), Authorization (verify permissions), Accounting (track actions). AAA framework: Authentication, Authorization, Accounting — implemented via RADIUS, TACACS+, or LDAP/SAML/OAuth.',
    tags: ['cia-triad', 'fundamentals', 'aaa', 'non-repudiation'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-1.1', 'SEC-1.3'],
    detection: 'Security posture assessment against CIA objectives',
    mitigation: 'Design all security controls to address one or more CIA objectives, implement AAA framework'
  },
  {
    id: 'SEC-1.3',
    domain: 'comptia',
    title: 'Zero Trust Architecture',
    content: 'Zero Trust principle: never trust, always verify. Core tenets: verify explicitly (authenticate and authorize every access request based on all available data points), use least privilege access (JIT/JEA — just-in-time, just-enough-access), assume breach (minimize blast radius, segment access, verify end-to-end encryption, use analytics for threat detection). Implementation components: identity verification (MFA, conditional access), device validation (health checks, compliance), micro-segmentation (software-defined perimeters), continuous monitoring, policy decision/enforcement points (PDP/PEP). Control plane vs data plane separation. NIST SP 800-207 defines the architecture.',
    tags: ['zero-trust', 'architecture', 'identity', 'micro-segmentation'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-1.1', 'SEC-3.1'],
    detection: 'Zero trust maturity assessment, implicit trust identification, lateral movement risk analysis',
    mitigation: 'Implement zero trust architecture: strong identity verification, device compliance, micro-segmentation, continuous monitoring, least privilege'
  },
  {
    id: 'SEC-1.4',
    domain: 'comptia',
    title: 'Threat Actors and Motivations',
    content: 'Threat actor types: Nation-state (APT, espionage, sabotage — highest sophistication, persistent, well-funded), Organized crime (financial gain — ransomware, fraud, data theft), Hacktivists (ideological motivation — defacement, DDoS, data leaks), Insider threats (employees/contractors — highest trust level, hardest to detect), Script kiddies (low sophistication, use existing tools), Shadow IT (unmanaged technology within org). Attributes: internal vs external, level of sophistication/capability, resources/funding, intent/motivation. Attack vectors: direct access, wireless, email, supply chain, social media, removable media, cloud.',
    tags: ['threat-actors', 'threat-intelligence', 'risk', 'apt'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1566', 'T1195'],
    relatedIds: ['SEC-2.1', 'SEC-2.2'],
    detection: 'Threat intelligence feeds, TTPs analysis, MITRE ATT&CK mapping, insider threat program',
    mitigation: 'Threat intelligence program, defense-in-depth aligned to threat actor capabilities, insider threat program, supply chain security'
  },
  {
    id: 'SEC-1.5',
    domain: 'comptia',
    title: 'Social Engineering Techniques',
    content: 'Phishing: mass email with malicious links/attachments. Spear phishing: targeted phishing at specific individuals. Whaling: phishing targeting executives. Vishing: voice-based phishing over phone. Smishing: SMS-based phishing. Pretexting: fabricated scenario to gain trust and extract information. Business Email Compromise (BEC): impersonating executives for wire transfers. Watering hole: compromising websites frequented by targets. Typosquatting: registering misspelled domains. Brand impersonation: fake sites/emails mimicking trusted brands. Principles exploited: authority, urgency, scarcity, social proof, familiarity, trust, intimidation.',
    tags: ['social-engineering', 'phishing', 'human-factor', 'awareness'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1566', 'T1598', 'T1204'],
    relatedIds: ['SEC-1.4', 'SEC-2.1'],
    detection: 'Phishing simulation results, email gateway logs, reported suspicious emails, domain monitoring',
    mitigation: 'Security awareness training, phishing simulations, email filtering (SPF/DKIM/DMARC), URL sandboxing, MFA to limit credential theft impact'
  },
  {
    id: 'SEC-1.6',
    domain: 'comptia',
    title: 'Cryptographic Concepts',
    content: 'Symmetric encryption: same key for encrypt/decrypt (AES-256, ChaCha20 — fast, used for bulk data). Asymmetric encryption: public/private key pair (RSA, ECC — slower, used for key exchange and digital signatures). Hashing: one-way function producing fixed-length digest (SHA-256, SHA-3 — integrity verification, password storage). Digital signatures: hash + private key encryption (non-repudiation, integrity). Key exchange: Diffie-Hellman, ECDH. Salting: random data added before hashing to prevent rainbow table attacks. Key stretching: PBKDF2, bcrypt, scrypt — make brute force expensive. Steganography: hiding data within other data. Obfuscation: making code/data harder to understand.',
    tags: ['cryptography', 'encryption', 'hashing', 'pki'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-327', 'CWE-326'],
    mitreIds: [],
    relatedIds: ['SEC-3.6', 'SEC-3.7'],
    detection: 'Cryptographic algorithm audit, weak cipher detection, key management review',
    mitigation: 'Use AES-256 for symmetric, RSA-2048+/ECDSA for asymmetric, SHA-256+ for hashing, proper key management, retire weak algorithms'
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 2: Threats, Vulnerabilities, and Mitigations (22%)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'SEC-2.1',
    domain: 'comptia',
    title: 'Malware Types and Indicators',
    content: 'Virus: self-replicating code attached to host file, needs user action to spread. Worm: self-replicating, spreads without user interaction via network. Trojan: malicious code disguised as legitimate software. Ransomware: encrypts data, demands payment (double extortion: encrypt + exfiltrate). Spyware: covert data collection (keyloggers, screen capture). Rootkit: deep system compromise, hides from OS, kernel-level persistence. RAT (Remote Access Trojan): remote control of compromised system. Logic bomb: triggers on condition (date, event). Fileless malware: operates in memory, uses living-off-the-land binaries (LOLBins). Cryptominer: hijacks compute for cryptocurrency mining. Indicators: unusual network traffic, unexpected processes, file system changes, registry modifications, CPU/memory spikes.',
    tags: ['malware', 'virus', 'ransomware', 'rootkit', 'threats'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1204', 'T1059', 'T1055', 'T1486'],
    relatedIds: ['SEC-2.2', 'SEC-2.5'],
    detection: 'EDR/antivirus alerts, behavioral analysis, memory forensics, network traffic analysis, file integrity monitoring',
    mitigation: 'EDR/XDR deployment, application allowlisting, network segmentation, email filtering, user awareness, immutable backups for ransomware resilience'
  },
  {
    id: 'SEC-2.2',
    domain: 'comptia',
    title: 'Network-Based Attack Types',
    content: 'On-path attack (MITM): intercepting/modifying communications between two parties. ARP poisoning: falsifying ARP messages to redirect traffic. DNS poisoning/spoofing: corrupting DNS cache to redirect traffic. DDoS: overwhelming a target with traffic (volumetric, protocol, application layer). Amplification attacks: exploiting protocols (DNS, NTP, Memcached) for traffic multiplication. Replay attack: capturing and retransmitting valid data transmissions. SSL stripping: downgrading HTTPS to HTTP. MAC flooding: overwhelming switch CAM table to force hub behavior. VLAN hopping: accessing traffic on other VLANs via double-tagging or switch spoofing.',
    tags: ['network-attacks', 'ddos', 'mitm', 'dns', 'threats'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-300', 'CWE-350'],
    mitreIds: ['T1557', 'T1498', 'T1040'],
    relatedIds: ['SEC-2.1', 'SEC-2.3', 'SEC-3.1'],
    detection: 'IDS/IPS alerts, NetFlow analysis, DNS query monitoring, ARP table monitoring, traffic anomaly detection',
    mitigation: 'TLS everywhere, DNSSEC, port security, DHCP snooping, dynamic ARP inspection, DDoS protection services, HSTS, certificate pinning'
  },
  {
    id: 'SEC-2.3',
    domain: 'comptia',
    title: 'Application-Level Attack Types',
    content: 'SQL injection (SQLi): inserting SQL commands via user input to manipulate databases. Cross-site scripting (XSS): injecting client-side scripts — stored (persistent), reflected, DOM-based. Cross-site request forgery (CSRF): forcing authenticated user to submit unintended requests. Server-side request forgery (SSRF): making server perform requests to unintended locations. Directory traversal: accessing files outside intended directory using ../. Buffer overflow: writing beyond allocated memory boundaries. Race condition/TOCTOU: exploiting timing between check and use. API attacks: broken authentication, excessive data exposure, mass assignment, injection. Privilege escalation: gaining higher access than authorized (vertical) or accessing other users\' resources (horizontal).',
    tags: ['application-attacks', 'injection', 'xss', 'sqli', 'web-security'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-89', 'CWE-79', 'CWE-352', 'CWE-918', 'CWE-22', 'CWE-120'],
    mitreIds: ['T1190', 'T1059'],
    relatedIds: ['SEC-2.2', 'SEC-2.4'],
    detection: 'WAF alerts, SAST/DAST findings, log analysis for injection patterns, input validation failures',
    mitigation: 'Input validation, parameterized queries, output encoding, CSRF tokens, content security policy, WAF, secure coding training, regular DAST/SAST'
  },
  {
    id: 'SEC-2.4',
    domain: 'comptia',
    title: 'Password and Credential Attacks',
    content: 'Brute force: trying all possible combinations until successful. Dictionary attack: using wordlists of common passwords. Password spraying: trying common passwords across many accounts (avoids lockout). Credential stuffing: using stolen username/password pairs from breaches on other services. Rainbow table: precomputed hash-to-password lookup table (defeated by salting). Pass-the-hash: using captured NTLM hash to authenticate without knowing password. Kerberoasting: requesting service tickets and cracking them offline. Golden ticket: forging Kerberos TGT with stolen krbtgt hash for persistent domain access.',
    tags: ['password-attacks', 'credential-theft', 'brute-force', 'authentication'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-521', 'CWE-307', 'CWE-522'],
    mitreIds: ['T1110', 'T1003', 'T1558'],
    relatedIds: ['SEC-2.3', 'SEC-4.6'],
    detection: 'Failed login monitoring, account lockout alerts, credential leak monitoring, Kerberos anomaly detection',
    mitigation: 'MFA, password complexity policies, account lockout, credential leak monitoring, salted hashing (bcrypt), privileged access management, LAPS for local admin'
  },
  {
    id: 'SEC-2.5',
    domain: 'comptia',
    title: 'Vulnerability Types and Indicators',
    content: 'Software vulnerabilities: unpatched software, zero-day exploits, buffer overflows, memory leaks, race conditions. Configuration vulnerabilities: default credentials, open permissions, unnecessary services, weak cipher suites, missing security headers. Architecture vulnerabilities: single points of failure, improper network segmentation, lack of encryption, missing access controls. Human vulnerabilities: lack of training, social engineering susceptibility, improper data handling. Supply chain vulnerabilities: third-party software risks, hardware implants, compromised updates. Indicators of compromise (IoC): unusual outbound traffic, DNS anomalies, unexpected registry changes, unusual login patterns, data exfiltration signatures.',
    tags: ['vulnerabilities', 'ioc', 'indicators', 'weakness'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-16', 'CWE-1188'],
    mitreIds: ['T1190', 'T1195'],
    relatedIds: ['SEC-2.1', 'SEC-2.6'],
    detection: 'Vulnerability scanning, penetration testing, configuration auditing, IoC monitoring, threat intelligence',
    mitigation: 'Patch management, configuration hardening, architecture review, security training, supply chain risk management, continuous monitoring'
  },
  {
    id: 'SEC-2.6',
    domain: 'comptia',
    title: 'Mitigation Techniques',
    content: 'Patching: apply security updates promptly (critical: 15 days, high: 30 days). Hardening: disable unnecessary services, remove default accounts, apply CIS Benchmarks. Segmentation: isolate networks/systems to limit blast radius. Encryption: protect data at rest (AES-256) and in transit (TLS 1.3). Access control: implement least privilege, MFA, role-based access. Monitoring: deploy SIEM, EDR, IDS/IPS for detection. Decommissioning: securely retire end-of-life systems. Change management: formal process for system modifications. Configuration enforcement: infrastructure as code, policy-as-code. Application security: SAST, DAST, SCA in CI/CD pipeline.',
    tags: ['mitigation', 'hardening', 'patching', 'remediation'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-2.5', 'SEC-1.1'],
    detection: 'Patch compliance rate, hardening compliance, segmentation effectiveness, encryption coverage',
    mitigation: 'Layer mitigation techniques: patch + harden + segment + encrypt + monitor + access control for defense-in-depth'
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 3: Security Architecture (18%)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'SEC-3.1',
    domain: 'comptia',
    title: 'Network Security Architecture',
    content: 'Network segmentation: separate networks by function/sensitivity (VLANs, subnets, SDN). DMZ: buffer zone between trusted and untrusted networks for public-facing services. Firewall types: packet filtering (L3/L4), stateful inspection (connection tracking), next-gen (L7 application awareness, IPS, SSL inspection). Jump server/bastion host: single hardened access point to sensitive networks. Network Access Control (NAC): 802.1X — verify device identity and posture before network access. Software-defined networking (SDN): centralized, programmable network management. East-west traffic monitoring: detect lateral movement within network. IDS/IPS placement: at network boundaries and critical internal segments.',
    tags: ['network-security', 'firewall', 'segmentation', 'dmz', 'architecture'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1046', 'T1021'],
    relatedIds: ['SEC-3.2', 'SEC-3.3', 'SEC-1.3'],
    detection: 'Network architecture review, firewall rule audit, segmentation testing, NAC compliance check',
    mitigation: 'Defense-in-depth network design: perimeter firewalls + internal segmentation + NAC + IDS/IPS + micro-segmentation'
  },
  {
    id: 'SEC-3.2',
    domain: 'comptia',
    title: 'Secure Network Protocols',
    content: 'Secure replacements for insecure protocols: SSH (replaces Telnet, port 22), SFTP/SCP (replaces FTP, port 22), HTTPS (replaces HTTP, port 443), SNMPv3 (replaces SNMPv1/v2c — adds authentication and encryption), LDAPS (replaces LDAP, port 636), FTPS (FTP over TLS, port 990), DNSSEC (adds authentication to DNS). Email security: S/MIME (encryption + signatures), PGP/GPG (encryption), STARTTLS (opportunistic TLS for SMTP). Authentication protocols: SAML (web SSO), OAuth 2.0 (delegated authorization), OpenID Connect (authentication layer on OAuth), Kerberos (ticket-based, used in Active Directory). Always prefer encrypted protocol variants.',
    tags: ['protocols', 'network-security', 'encryption', 'authentication'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-319'],
    mitreIds: ['T1040', 'T1557'],
    relatedIds: ['SEC-3.1', 'SEC-1.6'],
    detection: 'Protocol version audit, cleartext protocol detection, certificate validation, cipher suite assessment',
    mitigation: 'Disable insecure protocols (Telnet, FTP, HTTP, SNMPv1/v2c), enforce TLS 1.2+, implement DNSSEC, use SSO with SAML/OIDC'
  },
  {
    id: 'SEC-3.3',
    domain: 'comptia',
    title: 'Cloud Security Architecture',
    content: 'Service models: IaaS (you manage OS up), PaaS (you manage app + data), SaaS (provider manages everything). Deployment: public (shared infrastructure), private (dedicated), hybrid (mixed), community (shared by specific group). Shared responsibility model: provider secures the cloud, customer secures what\'s in the cloud. Key controls: identity federation (SSO), CASB (cloud access security broker), CSPM (cloud security posture management), CWPP (cloud workload protection), encryption with customer-managed keys. Risks: data sovereignty, vendor lock-in, insecure APIs, misconfigured storage (S3 bucket exposure), insufficient logging.',
    tags: ['cloud-security', 'iaas', 'paas', 'saas', 'shared-responsibility'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1530', 'T1078'],
    relatedIds: ['SEC-3.1', 'SEC-3.4'],
    detection: 'CSPM scanning, cloud configuration audit, storage permission review, API security testing',
    mitigation: 'CASB deployment, CSPM continuous monitoring, encryption with CMK, IAM least privilege, cloud-native security tools, regular configuration audits'
  },
  {
    id: 'SEC-3.4',
    domain: 'comptia',
    title: 'Virtualization and Container Security',
    content: 'Hypervisor security: Type 1 (bare-metal, more secure) vs Type 2 (hosted). VM escape: breaking out of VM to access hypervisor or other VMs — critical vulnerability. VM sprawl: unmanaged proliferation of VMs increasing attack surface. Container security: minimal base images, no root user, read-only filesystem, vulnerability scanning of images, signed images, runtime security. Container orchestration (Kubernetes): RBAC, network policies, pod security standards, secrets management, admission controllers. Serverless security: function-level permissions, input validation, cold start security, dependency management. Infrastructure as Code: version-controlled, peer-reviewed, security-scanned templates.',
    tags: ['virtualization', 'containers', 'kubernetes', 'serverless', 'infrastructure'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1610', 'T1611'],
    relatedIds: ['SEC-3.3', 'SEC-3.5'],
    detection: 'Container image scanning, VM inventory audit, hypervisor patch status, K8s security benchmark',
    mitigation: 'Minimal base images, image signing, runtime protection, K8s pod security policies, IaC security scanning, VM lifecycle management'
  },
  {
    id: 'SEC-3.5',
    domain: 'comptia',
    title: 'IoT, ICS/SCADA, and Embedded System Security',
    content: 'IoT risks: default credentials, lack of encryption, no patch mechanism, weak authentication, large attack surface. ICS/SCADA: industrial control systems managing critical infrastructure (power, water, manufacturing). Operational Technology (OT) vs Information Technology (IT) convergence challenges. Key protocols: Modbus, DNP3, BACnet — often lack authentication/encryption. Purdue model: levels 0-5 for network segmentation. Security: air-gap or strictly segment OT from IT networks, monitor with OT-aware IDS, avoid direct internet exposure, maintain separate credential stores. Embedded systems: RTOS security, firmware update mechanisms, secure boot, hardware root of trust.',
    tags: ['iot', 'ics', 'scada', 'ot-security', 'embedded'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-798', 'CWE-311'],
    mitreIds: ['T1200'],
    relatedIds: ['SEC-3.1', 'SEC-3.4'],
    detection: 'IoT device inventory, OT network monitoring, firmware version audit, default credential scanning',
    mitigation: 'Network segmentation (Purdue model), change default credentials, OT-specific IDS, firmware updates, disable unnecessary protocols, restrict physical access'
  },
  {
    id: 'SEC-3.6',
    domain: 'comptia',
    title: 'PKI and Certificate Management',
    content: 'Public Key Infrastructure (PKI): framework for managing digital certificates and public-key encryption. Components: Certificate Authority (CA — issues and signs certs), Registration Authority (RA — verifies identity), Certificate Revocation List (CRL — list of revoked certs), Online Certificate Status Protocol (OCSP — real-time revocation check). Certificate types: DV (domain validation, basic), OV (organization validation, medium), EV (extended validation, highest assurance), wildcard (*.domain.com), SAN (Subject Alternative Name, multi-domain). Certificate lifecycle: request, issuance, renewal, revocation. Certificate pinning: binding a certificate to a host. Certificate transparency: public log of issued certificates to detect rogue certs. ACME protocol: automated certificate management (Let\'s Encrypt).',
    tags: ['pki', 'certificates', 'ca', 'tls', 'cryptography'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-295', 'CWE-296'],
    mitreIds: ['T1553'],
    relatedIds: ['SEC-1.6', 'SEC-3.7'],
    detection: 'Certificate expiration monitoring, revocation status checking, certificate transparency log review, CA trust audit',
    mitigation: 'Automated certificate management (ACME), certificate monitoring, short-lived certificates, OCSP stapling, certificate transparency monitoring'
  },
  {
    id: 'SEC-3.7',
    domain: 'comptia',
    title: 'Encryption Implementation and Use Cases',
    content: 'Data at rest: full-disk encryption (BitLocker, FileVault, LUKS), database TDE, file-level encryption. Data in transit: TLS 1.3 (web), IPsec (VPN), WireGuard (modern VPN), SSH (admin). Data in use: secure enclaves (Intel SGX, ARM TrustZone), homomorphic encryption (emerging). Key management: generation (hardware RNG), storage (HSM, KMS), rotation (automated, periodic), destruction (crypto-shredding). Blockchain: distributed, immutable ledger using cryptographic hashing. Quantum computing threat: RSA and ECC vulnerable to Shor\'s algorithm — NIST post-quantum cryptography standards (CRYSTALS-Kyber, CRYSTALS-Dilithium) being adopted. Start crypto agility planning now.',
    tags: ['encryption', 'key-management', 'data-protection', 'quantum'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-311', 'CWE-312', 'CWE-319'],
    mitreIds: [],
    relatedIds: ['SEC-1.6', 'SEC-3.6'],
    detection: 'Encryption coverage audit, key management review, weak algorithm detection, quantum readiness assessment',
    mitigation: 'Encrypt data at rest and in transit, HSM for key management, automated key rotation, crypto inventory, PQC migration roadmap'
  },
  {
    id: 'SEC-3.8',
    domain: 'comptia',
    title: 'Resilience and Redundancy',
    content: 'High availability: clustering, load balancing, failover. Geographic dispersal: multi-region, multi-AZ deployments. RAID levels: RAID 1 (mirroring), RAID 5 (striping with parity), RAID 6 (double parity), RAID 10 (mirroring + striping). Backup types: full (complete copy), incremental (changes since last backup), differential (changes since last full), snapshot (point-in-time). Replication: synchronous (real-time, zero RPO) vs asynchronous (near-real-time, non-zero RPO). Power: UPS (short-term), generator (long-term), PDU (distribution). Recovery metrics: RTO (recovery time objective — max acceptable downtime), RPO (recovery point objective — max acceptable data loss), MTTR (mean time to repair), MTBF (mean time between failures).',
    tags: ['resilience', 'redundancy', 'backup', 'high-availability', 'disaster-recovery'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1485', 'T1490'],
    relatedIds: ['SEC-3.3', 'SEC-4.3'],
    detection: 'Backup integrity verification, failover testing, RTO/RPO achievement measurement, single point of failure analysis',
    mitigation: '3-2-1 backup strategy, regular DR testing, multi-region deployment, defined RTO/RPO per system, immutable backups, automated failover'
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 4: Security Operations (28%)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'SEC-4.1',
    domain: 'comptia',
    title: 'Security Monitoring and SIEM',
    content: 'SIEM (Security Information and Event Management): centralized log collection, correlation, alerting, and reporting. Key features: log aggregation, real-time analysis, correlation rules, dashboards, compliance reporting, incident timeline reconstruction. Log sources: firewalls, IDS/IPS, servers, endpoints (EDR), cloud services, applications, authentication systems, DNS. SOAR (Security Orchestration, Automation, and Response): automates incident response workflows, playbook execution, enrichment. Key metrics: MTTD (mean time to detect), MTTC (mean time to contain), alert volume, false positive rate, analyst workload. Tuning: reduce noise, prioritize by risk, automate low-level responses.',
    tags: ['siem', 'monitoring', 'soar', 'logging', 'soc'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1070'],
    relatedIds: ['SEC-4.2', 'SEC-4.3', 'SEC-4.5'],
    detection: 'SIEM coverage assessment, correlation rule effectiveness, log source inventory, detection gap analysis',
    mitigation: 'Deploy SIEM with comprehensive log sources, tune correlation rules, implement SOAR for automation, 24/7 SOC coverage, regular detection engineering'
  },
  {
    id: 'SEC-4.2',
    domain: 'comptia',
    title: 'Incident Response Process',
    content: 'NIST SP 800-61r2 phases: 1) Preparation: IR plan, team, tools, training, communication plans. 2) Detection and Analysis: identify incidents, determine scope/impact, classify severity, document evidence. 3) Containment: short-term (isolate), long-term (patch/remediate while maintaining operations). 4) Eradication: remove threat actor access, eliminate malware, close vulnerabilities exploited. 5) Recovery: restore systems, verify integrity, monitor for re-compromise. 6) Post-incident/Lessons learned: conduct review within 2 weeks, update procedures, improve detection. Chain of custody: maintain evidence integrity for legal proceedings. Order of volatility: RAM > running processes > disk > network > removable media.',
    tags: ['incident-response', 'forensics', 'containment', 'eradication', 'recovery'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-4.1', 'SEC-4.3'],
    detection: 'IR process maturity assessment, tabletop exercise results, MTTD/MTTC/MTTR metrics',
    mitigation: 'Documented IR plan with playbooks, trained IR team, regular tabletop exercises, forensic toolkit prepared, pre-approved containment actions'
  },
  {
    id: 'SEC-4.3',
    domain: 'comptia',
    title: 'Digital Forensics',
    content: 'Evidence handling: identify, collect, preserve, analyze, present. Order of volatility (collect most volatile first): CPU registers/cache, RAM, swap/page file, disk, remote logging, physical configuration, archival media. Forensic imaging: bit-for-bit copy (dd, FTK Imager), hash verification (MD5/SHA-256 before and after). Write blockers: prevent evidence modification during acquisition. Chain of custody: document who handled evidence, when, where, why. Timeline analysis: reconstruct sequence of events from multiple sources. Network forensics: packet capture (Wireshark, tcpdump), NetFlow analysis, DNS logs. Memory forensics: Volatility framework for RAM analysis (malware detection, process investigation). Legal hold: preserve all relevant data when litigation is anticipated. E-discovery: electronic evidence identification and production for legal proceedings.',
    tags: ['forensics', 'evidence', 'chain-of-custody', 'investigation'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-4.2', 'SEC-4.4'],
    detection: 'Forensic readiness assessment, evidence preservation capability, toolset inventory',
    mitigation: 'Forensic imaging tools ready, write blockers available, chain of custody procedures documented, forensic analysts trained, evidence storage secured'
  },
  {
    id: 'SEC-4.4',
    domain: 'comptia',
    title: 'Log Analysis and Data Sources',
    content: 'Critical log sources: firewall logs (connections allowed/denied), IDS/IPS (alerts and blocks), OS security logs (authentication, authorization, system events), application logs (errors, access, transactions), web server logs (requests, status codes, user agents), DNS logs (query patterns, anomalous lookups), DHCP logs (IP assignments), email gateway (spam, phishing, malware), proxy/web filter (URL categories, blocked sites), cloud audit logs (CloudTrail, Azure Activity Log, GCP Audit Logs). Analysis techniques: pattern matching, anomaly detection, baseline comparison, statistical analysis, correlation across sources. Common indicators: impossible travel, off-hours access, failed login spikes, DNS to suspicious domains, large data transfers, encoded/encrypted outbound channels.',
    tags: ['logging', 'analysis', 'data-sources', 'siem', 'detection'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-778'],
    mitreIds: ['T1070', 'T1562.002'],
    relatedIds: ['SEC-4.1', 'SEC-4.3'],
    detection: 'Log source coverage audit, log retention verification, parsing accuracy check, correlation rule testing',
    mitigation: 'Centralized logging, standardized log format, retention policies (min 1 year), tamper-proof storage, automated alerting on critical indicators'
  },
  {
    id: 'SEC-4.5',
    domain: 'comptia',
    title: 'Vulnerability Management Lifecycle',
    content: 'Lifecycle phases: 1) Discovery: identify all assets (you can\'t scan what you don\'t know about). 2) Prioritization: risk-rank findings using CVSS, asset criticality, exploitability, business context. 3) Assessment: validate findings (reduce false positives), determine remediation approach. 4) Remediation: patch, reconfigure, compensating control, or accept risk with documentation. 5) Verification: rescan to confirm fix, regression testing. 6) Reporting: track metrics, trend analysis, compliance evidence. Scanning types: authenticated (credentialed — more accurate) vs unauthenticated (external perspective). CVSS scoring: Base (0-10, inherent severity), Temporal (changes over time), Environmental (context-specific). SLA targets: Critical (CVSS 9.0+) within 15 days, High (7.0-8.9) within 30 days, Medium (4.0-6.9) within 90 days, Low (0.1-3.9) within 180 days.',
    tags: ['vulnerability-management', 'scanning', 'cvss', 'remediation', 'patching'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1190', 'T1203'],
    relatedIds: ['SEC-2.5', 'SEC-2.6'],
    detection: 'Scan coverage metrics, remediation SLA compliance, mean-time-to-remediate, exception tracking',
    mitigation: 'Continuous vulnerability scanning, risk-based prioritization, automated patching where possible, exception management process, regular reporting to leadership'
  },
  {
    id: 'SEC-4.6',
    domain: 'comptia',
    title: 'Identity and Access Management (IAM)',
    content: 'Identity lifecycle: provisioning, management, deprovisioning. Directory services: Active Directory, LDAP, Azure AD/Entra ID. Federation: SAML, OAuth 2.0, OpenID Connect — enable SSO across organizational boundaries. MFA factors: knowledge (password, PIN), possession (token, phone, smart card), inherence (fingerprint, face, iris), location (GPS, IP), behavior (typing pattern). Passwordless authentication: FIDO2/WebAuthn, biometrics, certificate-based. Privileged Access Management (PAM): vault credentials, just-in-time access, session recording, emergency break-glass. Conditional access: grant/deny based on risk signals (device compliance, location, user risk level, sign-in risk). Account types: user, service, shared, guest — each with different risk profiles and controls.',
    tags: ['iam', 'identity', 'mfa', 'sso', 'pam', 'access-management'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-287', 'CWE-306'],
    mitreIds: ['T1078', 'T1110'],
    relatedIds: ['SEC-1.2', 'SEC-2.4', 'SEC-4.7'],
    detection: 'IAM configuration audit, MFA adoption rate, PAM usage metrics, orphan account identification, excessive permissions review',
    mitigation: 'Centralized IAM, MFA for all users, phishing-resistant auth (FIDO2), PAM for privileged accounts, automated provisioning/deprovisioning, regular access reviews'
  },
  {
    id: 'SEC-4.7',
    domain: 'comptia',
    title: 'Authorization and Access Control Models',
    content: 'Discretionary Access Control (DAC): resource owner controls access (file permissions in Windows/Linux). Mandatory Access Control (MAC): system-enforced based on labels/classifications (SELinux, military systems). Role-Based Access Control (RBAC): access based on assigned roles (most common in enterprises). Attribute-Based Access Control (ABAC): dynamic access decisions based on attributes (user, resource, environment, action). Rule-Based Access Control: access based on defined rules (firewall ACLs, time-based restrictions). Permission assignment principles: least privilege, separation of duties, need-to-know. File system permissions: read, write, execute, owner, group, others (Linux chmod). Access control enforcement at: network (firewall/ACL), application (authorization logic), data (row-level security, column masking).',
    tags: ['authorization', 'access-control', 'rbac', 'abac', 'permissions'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-285', 'CWE-862', 'CWE-863'],
    mitreIds: ['T1068', 'T1548'],
    relatedIds: ['SEC-4.6', 'SEC-1.1'],
    detection: 'Permission review, role analysis, excessive access identification, separation of duties violation check',
    mitigation: 'Implement RBAC or ABAC, enforce least privilege, regular access reviews, automated permission analysis, separation of duties controls'
  },
  {
    id: 'SEC-4.8',
    domain: 'comptia',
    title: 'Automation and Scripting in Security',
    content: 'Use cases: automated incident response (SOAR playbooks), vulnerability scanning orchestration, log analysis, threat intelligence enrichment, compliance checking, user provisioning/deprovisioning, IOC extraction, phishing triage. Scripting languages: Python (security automation standard), PowerShell (Windows administration/forensics), Bash (Linux automation). APIs: REST APIs for security tool integration, webhook-driven automation. Infrastructure as Code (IaC): Terraform, CloudFormation — version-controlled, auditable infrastructure. Policy as Code: Open Policy Agent (OPA), Sentinel — automated compliance checking. CI/CD security: automated SAST, DAST, SCA, secrets scanning in pipeline. Benefits: consistency, speed, scalability, reduced human error. Risks: automation of wrong actions, credential management for scripts, error propagation.',
    tags: ['automation', 'scripting', 'soar', 'devops', 'iac'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-4.1', 'SEC-4.5'],
    detection: 'Automation coverage assessment, script repository review, API security audit',
    mitigation: 'SOAR platform for IR automation, IaC for infrastructure, CI/CD security gates, secure credential management for scripts, peer review for automation code'
  },
  {
    id: 'SEC-4.9',
    domain: 'comptia',
    title: 'Endpoint Security',
    content: 'Endpoint Detection and Response (EDR): behavioral analysis, threat detection, investigation, and response on endpoints. Extended Detection and Response (XDR): correlates across endpoints, network, cloud, email. Antivirus/antimalware: signature-based + heuristic + behavioral + machine learning. Host-based firewall: control inbound/outbound connections per host. Host-based IDS/IPS (HIDS/HIPS): monitor system calls, file access, registry changes. Application allowlisting/denylisting: control which software can execute. Data Loss Prevention (DLP): monitor/block sensitive data exfiltration via endpoints. Mobile Device Management (MDM): enforce policies on mobile devices (encryption, remote wipe, app management). Full disk encryption: BitLocker (Windows), FileVault (macOS), LUKS (Linux). Boot integrity: Secure Boot, Measured Boot, UEFI.',
    tags: ['endpoint-security', 'edr', 'xdr', 'dlp', 'mdm'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1059', 'T1055', 'T1204'],
    relatedIds: ['SEC-4.1', 'SEC-2.1'],
    detection: 'EDR coverage verification, endpoint compliance check, DLP alert review, MDM enrollment audit',
    mitigation: 'EDR/XDR on all endpoints, full disk encryption, application allowlisting, DLP policies, MDM for mobile, secure boot enabled, patch management'
  },
  {
    id: 'SEC-4.10',
    domain: 'comptia',
    title: 'Email Security',
    content: 'SPF (Sender Policy Framework): DNS TXT record specifying authorized mail servers for domain — prevents sender address forgery. DKIM (DomainKeys Identified Mail): cryptographic signature on emails proving message integrity and sender authenticity. DMARC (Domain-based Message Authentication, Reporting, and Conformance): policy telling receivers how to handle SPF/DKIM failures (none, quarantine, reject). Email gateway: anti-spam, anti-phishing, anti-malware, URL rewriting/sandboxing, attachment sandboxing. S/MIME: email encryption and digital signatures using certificates. Data Loss Prevention: scan outbound email for sensitive data. Security awareness: train users to identify phishing, report suspicious emails. Implement all three (SPF + DKIM + DMARC) for effective email authentication.',
    tags: ['email-security', 'spf', 'dkim', 'dmarc', 'phishing-prevention'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1566', 'T1534'],
    relatedIds: ['SEC-1.5', 'SEC-4.9'],
    detection: 'DMARC report analysis, email gateway effectiveness metrics, phishing simulation results, SPF/DKIM failure monitoring',
    mitigation: 'SPF + DKIM + DMARC (reject policy), email gateway with sandboxing, user awareness training, phishing simulations, URL rewriting'
  },

  // ═══════════════════════════════════════════════════════════════
  // Domain 5: Security Program Management and Oversight (20%)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'SEC-5.1',
    domain: 'comptia',
    title: 'Governance and Policy Framework',
    content: 'Governance hierarchy: Laws/regulations > Standards > Policies > Procedures > Guidelines > Baselines. Policy types: Acceptable Use Policy (AUP), Information Security Policy, Data Classification Policy, Incident Response Policy, Password Policy, Remote Access Policy, BYOD Policy, Change Management Policy. Standards: mandatory requirements implementing policy (e.g., "all passwords must be 14+ characters"). Procedures: step-by-step instructions for specific tasks. Guidelines: recommended practices (non-mandatory). Baselines: minimum security configuration requirements. Governance structures: Board of directors (oversight), CISO (strategic leadership), Security steering committee (cross-functional decisions), Data owners (classification and access decisions).',
    tags: ['governance', 'policy', 'compliance', 'standards', 'management'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.2', 'SEC-5.3', 'SEC-1.1'],
    detection: 'Policy review cycle compliance, policy awareness assessment, governance structure audit',
    mitigation: 'Comprehensive policy framework, annual review cycle, executive sponsorship, employee acknowledgment, policy exception process'
  },
  {
    id: 'SEC-5.2',
    domain: 'comptia',
    title: 'Risk Management Process',
    content: 'Risk identification: asset inventory, threat analysis, vulnerability assessment. Risk analysis: qualitative (High/Medium/Low) or quantitative (ALE = ARO x SLE, where ALE = Annualized Loss Expectancy, ARO = Annualized Rate of Occurrence, SLE = Single Loss Expectancy). Risk response: Mitigate/reduce (implement controls), Transfer/share (insurance, contracts), Accept (document and acknowledge), Avoid (eliminate activity). Risk register: centralized log of identified risks with owner, status, treatment plan. Risk appetite: amount of risk organization is willing to accept. Risk tolerance: acceptable variation from risk appetite. Risk threshold: level triggering action. Risk matrix: likelihood x impact grid. Key Risk Indicators (KRI): metrics that signal rising risk. Residual risk: risk remaining after controls are applied. Inherent risk: risk before controls.',
    tags: ['risk-management', 'risk-assessment', 'quantitative', 'qualitative', 'governance'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.1', 'SEC-5.3'],
    detection: 'Risk register review, risk assessment currency, KRI monitoring, residual risk evaluation',
    mitigation: 'Formal risk management framework, regular risk assessments, risk register maintenance, defined risk appetite, risk-based decision making'
  },
  {
    id: 'SEC-5.3',
    domain: 'comptia',
    title: 'Compliance and Regulatory Frameworks',
    content: 'Key regulations: GDPR (EU data protection — 72-hour breach notification, right to erasure, data minimization), HIPAA (US healthcare — PHI protection, BAAs), PCI DSS (payment card data — 12 requirements), SOX (US financial reporting — IT controls for financial systems), CCPA/CPRA (California privacy), FERPA (US education records), GLBA (US financial services). Frameworks: NIST CSF (risk-based, voluntary), ISO 27001 (ISMS certification), CIS Controls (prioritized security actions), COBIT (IT governance), SOC 2 (service organization controls — Type I point-in-time, Type II over period). Compliance != security, but compliance drives minimum standards. Audit types: internal, external, regulatory, third-party. Non-compliance consequences: fines, legal action, reputational damage, loss of business.',
    tags: ['compliance', 'regulatory', 'gdpr', 'hipaa', 'pci-dss', 'frameworks'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.1', 'SEC-5.2'],
    detection: 'Compliance audit results, gap analysis, regulatory change monitoring, control effectiveness testing',
    mitigation: 'Map controls to regulatory requirements, continuous compliance monitoring, annual audits, regulatory change tracking, compliance automation tools'
  },
  {
    id: 'SEC-5.4',
    domain: 'comptia',
    title: 'Security Awareness and Training Program',
    content: 'Program components: onboarding training, annual refresher, role-based training (developers, admins, executives), phishing simulations, security champions program. Topics: social engineering recognition, password hygiene, data handling, incident reporting, physical security, remote work security, insider threat awareness. Metrics: training completion rate, phishing click rate (target <5%), reported incident rate, time-to-report phishing. Methods: CBT (computer-based training), gamification, tabletop exercises, lunch-and-learns, security newsletters. Executive training: business email compromise, board-level reporting, risk acceptance responsibilities. Developer training: secure coding (OWASP Top 10), dependency management, secrets management. Effectiveness: measure behavior change, not just completion.',
    tags: ['training', 'awareness', 'phishing', 'human-factor', 'culture'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1566', 'T1204'],
    relatedIds: ['SEC-1.5', 'SEC-5.1'],
    detection: 'Training completion metrics, phishing simulation results, security incident trends, user reporting rates',
    mitigation: 'Comprehensive awareness program, quarterly phishing simulations, role-based training, security champions, behavior-based metrics'
  },
  {
    id: 'SEC-5.5',
    domain: 'comptia',
    title: 'Auditing and Assessment Types',
    content: 'Assessment types: Vulnerability assessment (identify weaknesses), Penetration testing (exploit weaknesses to prove impact), Security audit (compliance verification), Risk assessment (identify and evaluate risks). Pentest types: black box (no prior knowledge), white box (full knowledge), gray box (partial knowledge). Pentest methodology: reconnaissance, scanning, gaining access, maintaining access, covering tracks, reporting. Rules of engagement: scope, timing, authorized actions, emergency contacts, reporting requirements. Red team: adversary simulation (multi-vector, long-term). Blue team: defenders (detection and response). Purple team: collaboration between red and blue. Bug bounty: crowdsourced vulnerability discovery. Audit standards: NIST SP 800-53A (assessment guide), ISO 27001 (certification audit), SSAE 18 (SOC reports).',
    tags: ['auditing', 'assessment', 'pentest', 'red-team', 'compliance'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.3', 'SEC-4.5'],
    detection: 'Assessment schedule compliance, finding trend analysis, remediation tracking, audit readiness evaluation',
    mitigation: 'Regular vulnerability assessments, annual penetration testing, periodic audits, red team exercises, bug bounty program for mature organizations'
  },
  {
    id: 'SEC-5.6',
    domain: 'comptia',
    title: 'Data Classification and Lifecycle',
    content: 'Classification levels (example): Public (no impact if disclosed), Internal/Private (limited internal impact), Confidential (significant business impact), Restricted/Secret (severe impact — PII, PHI, financial). Data states: at rest (stored), in transit (moving), in use (being processed). Data lifecycle: Create/collect, Store, Use, Share, Archive, Destroy. Data types requiring protection: PII (personally identifiable information), PHI (protected health information), financial data, intellectual property, legal privilege. Data roles: Data owner (classifies, accountable), Data custodian (implements controls, manages storage), Data steward (ensures quality and compliance), Data processor (processes on behalf of controller), Data controller (determines processing purposes). Data sovereignty: data subject to laws of country where stored. Data minimization: collect only what\'s necessary.',
    tags: ['data-classification', 'data-protection', 'privacy', 'lifecycle', 'governance'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: ['CWE-200', 'CWE-359'],
    mitreIds: ['T1005', 'T1530'],
    relatedIds: ['SEC-5.1', 'SEC-5.3'],
    detection: 'Data discovery scanning, classification accuracy audit, data flow mapping, retention compliance check',
    mitigation: 'Data classification policy, automated discovery/classification tools, DLP enforcement, retention schedules, secure disposal, data minimization practice'
  },
  {
    id: 'SEC-5.7',
    domain: 'comptia',
    title: 'Third-Party and Supply Chain Risk Management',
    content: 'Vendor risk management: due diligence before engagement, risk assessment, ongoing monitoring. Assessment methods: security questionnaires (SIG, CAIQ), SOC 2 reports review, penetration test results, compliance certifications (ISO 27001, PCI DSS). Contractual controls: BAAs (HIPAA), DPAs (GDPR), SLAs, right to audit clauses, data handling requirements, breach notification requirements, cyber insurance requirements. Supply chain risks: software supply chain attacks (SolarWinds, Log4j), hardware tampering, third-party data breaches, vendor concentration risk. Software Bill of Materials (SBOM): inventory of software components and dependencies. Vendor access: least privilege, dedicated accounts, session monitoring, access review. Vendor tiering: classify by risk level (data access, criticality) and apply proportional controls.',
    tags: ['supply-chain', 'vendor-risk', 'third-party', 'sbom', 'procurement'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: ['T1195', 'T1199'],
    relatedIds: ['SEC-5.2', 'SEC-5.3'],
    detection: 'Vendor risk assessment review, SOC 2 report analysis, SBOM analysis, vendor access audit, supply chain monitoring',
    mitigation: 'Vendor risk management program, tiered assessment approach, contractual security requirements, SBOM management, continuous vendor monitoring'
  },
  {
    id: 'SEC-5.8',
    domain: 'comptia',
    title: 'Business Continuity and Disaster Recovery',
    content: 'Business Impact Analysis (BIA): identify critical processes, determine maximum tolerable downtime (MTD), establish RTO/RPO per system. BCP (Business Continuity Plan): maintain operations during disruption. DRP (Disaster Recovery Plan): restore IT systems after disaster. Recovery site types: hot site (fully operational, minutes RTO), warm site (partially equipped, hours RTO), cold site (shell facility, days/weeks RTO), cloud-based (on-demand infrastructure, variable RTO). Testing types: tabletop exercise (discussion-based), walkthrough (step-by-step review), simulation (simulated disaster), parallel test (activate backup while primary runs), full interruption (switch to backup, highest risk). COOP (Continuity of Operations): government term for business continuity. Succession planning: predetermined chain of authority during crisis.',
    tags: ['business-continuity', 'disaster-recovery', 'bcp', 'drp', 'resilience'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-3.8', 'SEC-5.2'],
    detection: 'BIA currency review, DR test results, RTO/RPO achievement, plan completeness assessment',
    mitigation: 'Annual BIA, documented BCP/DRP, regular testing (minimum annual), defined recovery site strategy, executive sponsorship, cross-training for key roles'
  },
  {
    id: 'SEC-5.9',
    domain: 'comptia',
    title: 'Change Management and Asset Management',
    content: 'Change management process: request, assess risk/impact, approve (CAB — Change Advisory Board), implement, verify, document. Change types: standard (pre-approved, low risk), normal (requires CAB approval), emergency (expedited approval, retrospective review). Change windows: scheduled maintenance periods to minimize impact. Rollback plan: required for every change — how to revert if implementation fails. Asset management: hardware inventory, software inventory, license management, lifecycle tracking (procurement to disposal). Configuration management: baselines, versioning, drift detection. CMDB (Configuration Management Database): centralized asset and relationship tracking. Shadow IT detection: identify unauthorized hardware/software/cloud services. End-of-life management: plan for unsupported systems (upgrade, replace, compensating controls).',
    tags: ['change-management', 'asset-management', 'cmdb', 'operations', 'governance'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.1', 'SEC-2.5'],
    detection: 'Change management compliance audit, unauthorized change detection, asset inventory accuracy, shadow IT discovery',
    mitigation: 'Formal change management process, CAB reviews, mandatory rollback plans, automated asset discovery, CMDB maintenance, shadow IT monitoring'
  },
  {
    id: 'SEC-5.10',
    domain: 'comptia',
    title: 'Security Metrics and Reporting',
    content: 'Key security metrics: Mean Time to Detect (MTTD), Mean Time to Contain (MTTC), Mean Time to Remediate (MTTR), patch compliance rate, vulnerability aging, phishing click rate, MFA adoption, security training completion, incidents per period, false positive rate, cost per incident. Reporting audiences: Board/executives (risk posture, business impact, trends), management (operational metrics, resource needs), technical (detailed findings, remediation status). Dashboards: real-time operational view vs periodic executive summary. KPIs vs KRIs: performance indicators measure program effectiveness, risk indicators signal rising risk. Benchmarking: compare metrics against industry peers. Maturity models: CMMI, NIST CSF tiers (Partial, Risk-Informed, Repeatable, Adaptive). Report frequency: real-time for SOC, monthly for management, quarterly for board.',
    tags: ['metrics', 'reporting', 'kpi', 'governance', 'maturity'],
    severity: 'info',
    references: ['https://www.comptia.org/certifications/security'],
    cweIds: [],
    mitreIds: [],
    relatedIds: ['SEC-5.1', 'SEC-5.2'],
    detection: 'Metrics collection completeness, reporting cadence compliance, data accuracy validation',
    mitigation: 'Define KPIs/KRIs aligned to business objectives, automate metrics collection, audience-appropriate reporting, regular benchmarking, maturity assessment'
  }
];

module.exports = { COMPTIA_SEC };
