'use strict';

const OWASP_WEB = [
  {
    id: 'A01:2021',
    domain: 'owasp-web',
    title: 'Broken Access Control',
    content: 'Access control enforces policy such that users cannot act outside their intended permissions. Failures lead to unauthorized info disclosure, modification, or destruction of data. Common issues: IDOR (Insecure Direct Object References), missing function-level access control, CORS misconfiguration allowing arbitrary origins, JWT tampering (algorithm confusion none/HS256/RS256, signature stripping, claim manipulation), path traversal via ../ sequences, metadata manipulation (hidden fields, cookies, JWT tokens), and privilege escalation through role parameter tampering. Exploits: Modify URL/API params to access other users\' data (e.g., /api/users/123 to /api/users/456). Force-browse to admin pages (/admin, /actuator, /debug). Manipulate access tokens to escalate privileges. Bypass access controls by replaying or tampering with JWT claims. Access API endpoints without proper authorization headers. This category moved from #5 in 2017 to #1 in 2021, reflecting how pervasive these failures are. 94% of applications tested had some form of broken access control. Notable mapped CWEs include CWE-22 (Path Traversal), CWE-23 (Relative Path Traversal), CWE-35 (Path Traversal), CWE-59 (Link Following), and CWE-200 (Exposure of Sensitive Information).',
    tags: ['access-control', 'authorization', 'idor', 'privilege-escalation', 'cors', 'jwt', 'path-traversal', 'force-browsing'],
    severity: 'critical',
    references: ['https://owasp.org/Top10/A01_2021-Broken_Access_Control/'],
    cweIds: ['CWE-200', 'CWE-284', 'CWE-285', 'CWE-352', 'CWE-639', 'CWE-22', 'CWE-35', 'CWE-862', 'CWE-863'],
    mitreIds: ['T1548', 'T1078'],
    relatedIds: ['A07:2021'],
    detection: 'Automated DAST scanning for IDOR (parameter tampering with authenticated sessions), code review for authorization checks at every endpoint, API fuzzing with horizontal/vertical privilege escalation tests, review CORS headers (Access-Control-Allow-Origin), check for missing anti-CSRF tokens, test JWT validation (try alg:none, key confusion), verify directory listing is disabled, check HTTP method override (X-HTTP-Method-Override)',
    mitigation: 'Deny by default except public resources. Implement robust RBAC/ABAC with centralized access control mechanism. Validate object ownership server-side on every request (never trust client-side IDs). Disable directory listing and ensure web root does not contain metadata files (.git, .svn). Rate limit API and controller access to minimize automated attack impact. Log and alert on access control failures. Invalidate JWT/session on server side after logout. Use CORS allowlists (never wildcard for authenticated endpoints). Implement resource-based authorization checks. Use indirect object references (mapping tables) instead of exposing DB keys.'
  },
  {
    id: 'A02:2021',
    domain: 'owasp-web',
    title: 'Cryptographic Failures',
    content: 'Previously known as "Sensitive Data Exposure" (2017), this category focuses on failures related to cryptography which often lead to sensitive data exposure. Includes: transmitting data in cleartext (HTTP, SMTP, FTP), using deprecated or weak cryptographic algorithms (MD5, SHA1, DES, RC4, RSA-1024), using hardcoded or default cryptographic keys, not enforcing TLS (missing HSTS, mixed content), improper certificate validation, using crypto functions without proper initialization vectors (static/predictable IVs), using ECB mode, missing authenticated encryption (using CBC without HMAC), password storage using reversible encryption instead of adaptive hashing, weak or missing key derivation functions, insufficient entropy in random number generation (using Math.random() for security purposes), and deprecated hash functions for password storage (unsalted MD5/SHA). Data in transit: sensitive data sent over HTTP, email protocols without TLS, database connections without encryption. Data at rest: plaintext storage of passwords/PII/financial data in databases, backups, log files.',
    tags: ['cryptography', 'encryption', 'tls', 'hashing', 'passwords', 'data-exposure', 'key-management'],
    severity: 'critical',
    references: ['https://owasp.org/Top10/A02_2021-Cryptographic_Failures/'],
    cweIds: ['CWE-259', 'CWE-261', 'CWE-296', 'CWE-310', 'CWE-319', 'CWE-321', 'CWE-327', 'CWE-328', 'CWE-329', 'CWE-330', 'CWE-331', 'CWE-335', 'CWE-336', 'CWE-338', 'CWE-522'],
    mitreIds: ['T1557', 'T1040', 'T1552'],
    relatedIds: ['A07:2021'],
    detection: 'Scan for cleartext protocols in code and config. Check TLS configuration (ssllabs.com, testssl.sh). Review password storage (look for MD5/SHA1/SHA256 without salt). Audit key management (hardcoded keys, keys in source control). Check for use of Math.random() or weak PRNGs in security context. Verify HSTS headers. Scan for sensitive data in logs. Review database connection strings for encryption settings. Check certificate pinning in mobile apps.',
    mitigation: 'Classify data by sensitivity and apply controls per classification. Do not store sensitive data unnecessarily; discard as soon as possible. Encrypt all data in transit with TLS 1.2+ (enforce via HSTS with includeSubDomains, preload). Encrypt data at rest with AES-256-GCM or ChaCha20-Poly1305. Use authenticated encryption (GCM, CCM) not unauthenticated modes (ECB, CBC without HMAC). Store passwords with bcrypt (cost 12+), scrypt, or Argon2id. Use CSPRNG for all random values (crypto.randomBytes, SecureRandom). Manage keys via HSM or dedicated key management service. Rotate keys regularly. Disable caching for responses containing sensitive data (Cache-Control: no-store).'
  },
  {
    id: 'A03:2021',
    domain: 'owasp-web',
    title: 'Injection',
    content: 'Injection flaws occur when an application sends untrusted data to an interpreter. This includes SQL injection, NoSQL injection, OS command injection, ORM injection, LDAP injection, Expression Language (EL) injection, and OGNL injection. Dropped from #1 in 2017 to #3 in 2021 due to improved frameworks with built-in parameterization, but still extremely dangerous. An application is vulnerable when: user-supplied data is not validated, filtered, or sanitized; dynamic queries or non-parameterized calls are used without context-aware escaping; hostile data is used in ORM search parameters; hostile data is directly used or concatenated in dynamic queries, commands, or stored procedures. Modern injection also includes GraphQL injection, template injection (SSTI), header injection (CRLF), and XPath injection. Cross-site scripting (XSS) is considered a form of injection against the browser and is included in this category for 2021. XSS types: Reflected (non-persistent, payload in URL/request), Stored (persistent, payload saved and served to other users), DOM-based (client-side JavaScript manipulates DOM unsafely using sources like location.hash, document.referrer).',
    tags: ['injection', 'sql-injection', 'xss', 'command-injection', 'nosql', 'ldap', 'graphql', 'ssti'],
    severity: 'critical',
    references: ['https://owasp.org/Top10/A03_2021-Injection/'],
    cweIds: ['CWE-20', 'CWE-74', 'CWE-75', 'CWE-77', 'CWE-78', 'CWE-79', 'CWE-80', 'CWE-89', 'CWE-90', 'CWE-94', 'CWE-643'],
    mitreIds: ['T1190', 'T1059'],
    relatedIds: ['A01:2021', 'A05:2021'],
    detection: 'Static analysis (SAST) to find unsanitized inputs flowing to interpreters. Dynamic analysis (DAST) with fuzzing (sqlmap, Burp, ZAP). Code review focusing on string concatenation in queries, eval(), exec(), system() calls. Check for template injection by injecting {{7*7}} or ${7*7}. Test XSS with polyglot payloads. Review ORM usage for raw query methods. Check for NoSQL operators ($gt, $ne, $regex) in MongoDB queries. Content-Security-Policy header review for XSS mitigation.',
    mitigation: 'Use parameterized queries (prepared statements) exclusively for SQL. Use ORM safely (avoid raw query methods). Apply server-side input validation with allowlists. Escape output contextually (HTML entity encoding, JavaScript escaping, URL encoding, CSS escaping). Implement Content-Security-Policy headers to mitigate XSS. Use LIMIT and other SQL controls to prevent mass data disclosure. For OS commands, avoid shell calls entirely; use language-native APIs. For NoSQL, sanitize and validate input types. For LDAP, use frameworks with parameterized LDAP queries. Implement WAF as defense-in-depth layer.'
  },
  {
    id: 'A04:2021',
    domain: 'owasp-web',
    title: 'Insecure Design',
    content: 'New category for 2021 focusing on risks related to design and architectural flaws. Insecure design is different from insecure implementation: even a perfect implementation of an insecure design is still vulnerable. This category calls for more use of threat modeling, secure design patterns, and reference architectures. Issues include: missing rate limiting on sensitive operations (password reset, OTP verification), credential stuffing due to lack of breach password checks, missing anti-automation controls (CAPTCHA, proof-of-work), insecure password recovery (security questions, predictable tokens), trust boundary violations (trusting client-side validation), missing fraud/abuse controls in business logic, unlimited resource consumption (file uploads, API calls), failure to segregate tenants in multi-tenant architectures, insecure by default configurations, and missing security requirements in design phase. Key difference from implementation bugs: design flaws cannot be fixed by a perfect implementation. Example: a movie theater chain allows group booking up to 15 seats without deposit. An attacker scripts all showings to reserve maximum seats, causing massive revenue loss. This is a design flaw, not an implementation bug.',
    tags: ['secure-design', 'threat-modeling', 'architecture', 'business-logic', 'abuse-cases', 'rate-limiting'],
    severity: 'high',
    references: ['https://owasp.org/Top10/A04_2021-Insecure_Design/'],
    cweIds: ['CWE-73', 'CWE-183', 'CWE-209', 'CWE-256', 'CWE-501', 'CWE-522', 'CWE-602', 'CWE-656'],
    mitreIds: [],
    relatedIds: ['A01:2021', 'A07:2021'],
    detection: 'Threat modeling during design phase (STRIDE, PASTA, attack trees). Abuse case and misuse case analysis. Architecture review by security architects. Business logic testing (transaction limits, workflow bypass, race conditions). Review for missing rate limiting and anti-automation. Check for trust boundary violations. Evaluate multi-tenancy isolation. Review credential recovery flows.',
    mitigation: 'Establish and use a secure development lifecycle (SDL) with security specialists. Build and use a library of secure design patterns and paved-road components. Use threat modeling for critical authentication, access control, business logic, and key flows. Integrate security language and controls into user stories. Integrate plausibility checks at each tier (frontend, backend, database). Write unit and integration tests to validate all critical flows are resistant to the threat model. Segregate tenant data and processing. Limit resource consumption by user/service. Implement rate limiting on all sensitive operations.'
  },
  {
    id: 'A05:2021',
    domain: 'owasp-web',
    title: 'Security Misconfiguration',
    content: 'Moved up from #6 in 2017. 90% of applications were tested for some form of misconfiguration. With increased adoption of highly configurable software, this category is growing. Includes: missing security hardening across any part of the application stack (OS, web server, app server, database, framework, VM, container, cloud service). Default credentials left active (admin/admin, root/toor). Unnecessary features enabled (ports, services, pages, accounts, privileges). Default accounts and passwords still enabled and unchanged. Error handling revealing stack traces or overly informative error messages. Disabled or improperly configured security features in frameworks/libraries. Missing security headers (X-Content-Type-Options, X-Frame-Options, Content-Security-Policy, Strict-Transport-Security). Outdated or vulnerable server/framework with insecure default settings. Cloud storage misconfiguration (S3 buckets public, Azure blobs exposed). Docker/Kubernetes misconfigurations (privileged containers, default service account tokens, exposed dashboards). XML external entities enabled by default. Missing TLS for internal services.',
    tags: ['misconfiguration', 'hardening', 'defaults', 'headers', 'cloud', 'docker', 'kubernetes', 'error-handling'],
    severity: 'high',
    references: ['https://owasp.org/Top10/A05_2021-Security_Misconfiguration/'],
    cweIds: ['CWE-2', 'CWE-11', 'CWE-13', 'CWE-15', 'CWE-16', 'CWE-388', 'CWE-489', 'CWE-497', 'CWE-611', 'CWE-614', 'CWE-756', 'CWE-776', 'CWE-942'],
    mitreIds: ['T1574', 'T1562'],
    relatedIds: ['A06:2021', 'A02:2021'],
    detection: 'Automated configuration scanning (ScoutSuite, Prowler for AWS, kube-bench for K8s). Security header analysis (securityheaders.com, Mozilla Observatory). Port scanning for unnecessary services. Review cloud IAM policies and storage ACLs. Check for default credentials (nuclei default-login templates). Review Docker images for running as root, unnecessary packages. Test error pages for information leakage. Verify TLS on all internal/external endpoints. Check for debug modes enabled in production.',
    mitigation: 'Implement repeatable hardening process (CIS Benchmarks) automated in CI/CD. Use minimal platform with no unnecessary features, components, documentation, or samples. Review and update configurations as part of patch management. Implement segmented application architecture with containerization or cloud security groups. Send security directives to clients via security headers. Automate verification of configuration and settings in all environments. Use separate credentials per environment, never share between dev/staging/prod. Remove or restrict all default accounts. Implement Infrastructure as Code (IaC) with security baselines.'
  },
  {
    id: 'A06:2021',
    domain: 'owasp-web',
    title: 'Vulnerable and Outdated Components',
    content: 'Previously "Using Components with Known Vulnerabilities" (2017, A9). Moved up from #9. An application is vulnerable if: you do not know the versions of all components (both client-side and server-side) including nested dependencies; software is vulnerable, unsupported, or out of date (OS, web/application server, DBMS, APIs, runtime environments, libraries, frameworks); you do not scan for vulnerabilities regularly and subscribe to security bulletins; you do not fix or upgrade the underlying platform, frameworks, and dependencies in a risk-based, timely fashion (common in monthly/quarterly patching environments leaving exposure for days or months); software developers do not test compatibility of updated, upgraded, or patched libraries; you do not secure component configurations (see A05). Real-world impact: CVE-2017-5638 (Apache Struts 2 RCE leading to Equifax breach), Log4Shell (CVE-2021-44228), Spring4Shell (CVE-2022-22965), and countless npm/PyPI supply chain attacks. Transitive dependencies are especially dangerous as they are invisible to developers.',
    tags: ['dependencies', 'components', 'supply-chain', 'sca', 'patching', 'libraries', 'frameworks'],
    severity: 'high',
    references: ['https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/'],
    cweIds: ['CWE-1035', 'CWE-1104'],
    mitreIds: ['T1195', 'T1190'],
    relatedIds: ['A05:2021', 'A08:2021'],
    detection: 'Software Composition Analysis (SCA) tools: Snyk, Dependabot, npm audit, OWASP Dependency-Check, Trivy, Grype. Monitor CVE databases and NVD feeds. Generate and maintain SBOM (Software Bill of Materials) with CycloneDX or SPDX. Continuously monitor for new vulnerabilities in dependencies. Check for end-of-life components. Audit lock files (package-lock.json, Gemfile.lock) for unexpected changes.',
    mitigation: 'Remove unused dependencies, features, components, files, documentation. Continuously inventory versions of all client-side and server-side components using tools like OWASP Dependency-Check, npm audit, retire.js. Monitor CVE and NVD continuously for vulnerabilities. Automate dependency updates with Dependabot/Renovate. Only obtain components from official sources over secure links. Prefer signed packages. Monitor for unmaintained or unpatched libraries. Implement virtual patching via WAF as interim measure. Create organizational policy for component governance. Pin dependency versions and use lock files.'
  },
  {
    id: 'A07:2021',
    domain: 'owasp-web',
    title: 'Identification and Authentication Failures',
    content: 'Previously "Broken Authentication" (2017, A2). Moved down from #2 due to increased availability of standardized frameworks. Confirmation of the user identity, authentication, and session management is critical. Authentication weaknesses exist when: the application permits automated attacks such as credential stuffing (the attacker has a list of valid usernames and passwords); the application permits brute force or other automated attacks; the application permits default, weak, or well-known passwords ("Password1", "admin/admin"); the application uses weak or ineffective credential recovery and forgot-password processes such as knowledge-based answers; the application uses plain text, encrypted, or weakly hashed password data stores; the application has missing or ineffective multi-factor authentication; the application exposes session identifier in the URL; the application reuses session identifier after successful login (session fixation); the application does not correctly invalidate session IDs or auth tokens (especially SSO tokens) during logout or inactivity. Modern issues also include: JWT implementation flaws (no expiration, weak secrets, algorithm confusion), OAuth/OIDC misconfigurations (open redirects, lax state parameter validation), API key exposure, and insufficient account lockout policies.',
    tags: ['authentication', 'session-management', 'credentials', 'mfa', 'brute-force', 'credential-stuffing', 'jwt', 'oauth'],
    severity: 'critical',
    references: ['https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/'],
    cweIds: ['CWE-255', 'CWE-256', 'CWE-257', 'CWE-287', 'CWE-288', 'CWE-290', 'CWE-294', 'CWE-295', 'CWE-297', 'CWE-300', 'CWE-302', 'CWE-304', 'CWE-306', 'CWE-307', 'CWE-346', 'CWE-384', 'CWE-521', 'CWE-613', 'CWE-620', 'CWE-640', 'CWE-798'],
    mitreIds: ['T1078', 'T1110', 'T1556'],
    relatedIds: ['A01:2021', 'A02:2021'],
    detection: 'Test for default credentials across all login interfaces. Brute force test with rate limit verification. Check password policy enforcement (minimum length, complexity, breached password check). Verify MFA implementation. Test session management (fixation, invalidation on logout, timeout). Review JWT implementation (algorithm, expiration, signature validation). Check for credential exposure in URLs, logs, error messages. Test account lockout and enumeration prevention. Verify OAuth state parameter and redirect URI validation.',
    mitigation: 'Implement multi-factor authentication to prevent credential stuffing, brute force, and stolen credential reuse. Do not ship or deploy with default credentials. Implement weak password checks (check against top 10000 worst passwords list, or use zxcvbn). Align password length, complexity, and rotation policies with NIST 800-63b guidelines (minimum 8 chars, allow up to 64+, no complexity rules, no rotation unless compromised). Harden registration, credential recovery, and API pathways against account enumeration (use identical responses). Limit or increasingly delay failed login attempts with account lockout (but beware DoS). Use server-side, secure session manager that generates random session ID with high entropy. Session ID must not be in URL, must be securely stored (HttpOnly, Secure, SameSite), and invalidated after logout/idle timeout.'
  },
  {
    id: 'A08:2021',
    domain: 'owasp-web',
    title: 'Software and Data Integrity Failures',
    content: 'New category for 2021. Relates to code and infrastructure that does not protect against integrity violations. Examples: application relies upon plugins, libraries, or modules from untrusted sources, repositories, and CDNs; an insecure CI/CD pipeline introduces the potential for unauthorized access, malicious code, or system compromise; auto-update functionality where updates are downloaded without sufficient integrity verification and applied to a previously trusted application; objects or data are encoded/serialized in a way that an attacker can see and modify (insecure deserialization). Insecure deserialization (previously A8:2017) is merged into this category. Deserialization attacks: Java ObjectInputStream, PHP unserialize(), Python pickle.loads(), .NET BinaryFormatter, Ruby Marshal.load(). Supply chain attacks: dependency confusion (private package name squatting on public registries), typosquatting (loadsh vs lodash), compromised maintainer accounts, malicious post-install scripts. CI/CD attacks: poisoned pipeline execution, compromised build artifacts, unsigned container images.',
    tags: ['integrity', 'deserialization', 'supply-chain', 'ci-cd', 'code-signing', 'subresource-integrity'],
    severity: 'high',
    references: ['https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/'],
    cweIds: ['CWE-345', 'CWE-353', 'CWE-426', 'CWE-494', 'CWE-502', 'CWE-565', 'CWE-784', 'CWE-829', 'CWE-830', 'CWE-915'],
    mitreIds: ['T1195', 'T1059'],
    relatedIds: ['A06:2021', 'A05:2021'],
    detection: 'Verify digital signatures on software/data. Audit CI/CD pipeline for unauthorized access or modifications. Review deserialization code for use of unsafe functions. Check npm/pip packages for suspicious postinstall scripts. Monitor for dependency confusion attacks. Verify Subresource Integrity (SRI) tags on CDN-loaded scripts. Review container image provenance and signatures. Scan for hardcoded serialization gadget chains. Monitor artifact repositories for tampering.',
    mitigation: 'Use digital signatures or similar mechanisms to verify software/data is from expected source and has not been altered. Ensure libraries and dependencies consume trusted repositories. Use tools like OWASP Dependency-Check to verify components do not contain known vulnerabilities. Ensure CI/CD pipeline has proper segregation, configuration, and access control to ensure integrity of code flowing through build and deploy processes. Ensure unsigned or unencrypted serialized data is not sent to untrusted clients without integrity checking or digital signature. Implement Subresource Integrity (SRI) for all CDN resources. Use code signing for releases. Implement allow-list for deserialization classes. Use JSON/protobuf instead of native serialization formats.'
  },
  {
    id: 'A09:2021',
    domain: 'owasp-web',
    title: 'Security Logging and Monitoring Failures',
    content: 'Previously "Insufficient Logging & Monitoring" (2017, A10). Moved up from #10. This category helps detect, escalate, and respond to active breaches. Without logging and monitoring, breaches cannot be detected. Insufficient logging, detection, monitoring, and active response occurs any time: auditable events (logins, failed logins, high-value transactions) are not logged; warnings and errors generate no, inadequate, or unclear log messages; logs are only stored locally and not aggregated; appropriate alerting thresholds and response escalation are not in place; penetration testing and scans by DAST tools do not trigger alerts; the application cannot detect, escalate, or alert for active attacks in real-time or near real-time. The average time to detect a breach is still over 200 days and is typically detected by external parties rather than internal monitoring. Logs must not contain sensitive data (passwords, tokens, PII in plain text) but must contain enough context for forensic analysis (who, what, when, where, outcome).',
    tags: ['logging', 'monitoring', 'detection', 'incident-response', 'siem', 'alerting', 'forensics'],
    severity: 'high',
    references: ['https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/'],
    cweIds: ['CWE-117', 'CWE-223', 'CWE-532', 'CWE-778'],
    mitreIds: ['T1562', 'T1070'],
    relatedIds: ['A01:2021', 'A07:2021'],
    detection: 'Audit log coverage (are all security-relevant events logged?). Test if logins, failed logins, access control failures, and input validation failures generate logs. Verify log integrity (can logs be tampered with?). Check if logs contain sufficient context for forensics. Review alerting rules for common attack patterns. Test incident response procedures. Verify logs do not contain sensitive data. Check log retention policies. Ensure centralized log aggregation is configured.',
    mitigation: 'Log all login, access control, and server-side input validation failures with sufficient user context to identify suspicious or malicious accounts, held long enough for delayed forensic analysis. Ensure logs are generated in a format that log management solutions can easily consume (structured logging, JSON format). Ensure log data is encoded correctly to prevent injection into logging systems (log injection/forging). Ensure high-value transactions have an audit trail with integrity controls to prevent tampering (append-only database tables, blockchain-style). Establish or adopt an incident response and recovery plan (NIST 800-61r2). Use SIEM with correlation rules. Set up real-time alerting for suspicious activities. Implement automated response (SOAR) for common attack patterns. Protect log infrastructure from tampering.'
  },
  {
    id: 'A10:2021',
    domain: 'owasp-web',
    title: 'Server-Side Request Forgery (SSRF)',
    content: 'New category added based on community survey (ranked #1 in community survey). SSRF flaws occur when a web application fetches a remote resource without validating the user-supplied URL. It allows an attacker to coerce the application to send a crafted request to an unexpected destination, even when protected by a firewall, VPN, or network ACL. As modern web applications provide convenient features to end users, fetching a URL has become common (webhooks, PDF generators, file importers, URL previews, RSS feed readers). The incidence and severity of SSRF is increasing due to cloud services and architectural complexity. Attack scenarios: scan internal networks from the web server (port scanning internal hosts), access cloud metadata services (AWS IMDSv1 at http://169.254.169.254/latest/meta-data/, GCP, Azure equivalents) to steal IAM credentials, read internal files via file:// protocol, access internal services (Redis, Elasticsearch, Memcached on localhost), exploit internal admin interfaces, DNS rebinding attacks to bypass allowlists, bypass through URL parsing inconsistencies (IP address encoding: decimal, octal, hex, IPv6 mapped IPv4), and redirect-based SSRF (30x redirect from allowed host to internal host).',
    tags: ['ssrf', 'server-side', 'cloud', 'metadata', 'internal-network', 'url-validation'],
    severity: 'critical',
    references: ['https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/'],
    cweIds: ['CWE-918'],
    mitreIds: ['T1090', 'T1190'],
    relatedIds: ['A01:2021', 'A05:2021'],
    detection: 'Test all URL input parameters for SSRF by submitting internal IPs (127.0.0.1, 10.x, 172.16-31.x, 192.168.x), cloud metadata URLs, file:// URIs, and alternative IP encodings. Use out-of-band detection (Burp Collaborator, interactsh) to detect blind SSRF. Check for URL parsing inconsistencies. Test redirect-based SSRF. Review code for HTTP client calls using user-supplied URLs. Check if IMDSv2 is enforced (blocks SSRF to AWS metadata). Test DNS rebinding scenarios.',
    mitigation: 'Sanitize and validate all client-supplied input URLs. Enforce URL schema, port, and destination with a positive allowlist. Do not send raw responses to clients (return only expected data, not full HTTP responses). Disable HTTP redirections in HTTP client libraries. Use allowlist-based DNS resolution and IP validation (validate resolved IP, not just hostname). Implement network-level segmentation: deploy SSRF-prone functionality in separate networks. Enforce IMDSv2 on all AWS instances (requires token-based header). Use firewall egress rules to restrict outbound connections from application servers. For URL preview/webhook features, use a dedicated proxy with strict egress controls. Implement response size limits and timeouts on outbound HTTP requests.'
  }
];

module.exports = { OWASP_WEB };
